# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'rails generate mailjet:initializerrails generate mailjet:initializer'
  config.secret_key = ''
  config.default_from = 'c'

end
